import { jsPDF } from "jspdf";
import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  ImageRun,
  AlignmentType,
} from "docx";
import { toJpeg, toPng } from "html-to-image";
import { canvasElRef } from "./canvasRef";

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

export function exportMermaidFile(mermaidText: string, processName: string) {
  const blob = new Blob([mermaidText], { type: "text/plain;charset=utf-8" });
  downloadBlob(blob, `${slug(processName)}.mmd`);
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

function slug(s: string): string {
  return s.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "process";
}

async function snapshotCanvas(): Promise<string | null> {
  const el = canvasElRef.current;
  if (!el) return null;
  try {
    return await toJpeg(el, { backgroundColor: "#ffffff", pixelRatio: 1.5, quality: 0.85 });
  } catch {
    return null;
  }
}

export async function exportPng(processName: string): Promise<boolean> {
  const el = canvasElRef.current;
  if (!el) return false;
  try {
    const dataUrl = await toPng(el, { backgroundColor: "#14161d", pixelRatio: 3, cacheBust: true });
    const blob = await (await fetch(dataUrl)).blob();
    downloadBlob(blob, `${slug(processName)}.png`);
    return true;
  } catch {
    return false;
  }
}

interface MdLine {
  kind: "h1" | "h2" | "h3" | "bullet" | "text" | "blank" | "numbered";
  text: string;
}

function parseMarkdownLines(md: string): MdLine[] {
  return md.split("\n").map((raw) => {
    const line = raw.trimEnd();
    if (!line.trim()) return { kind: "blank", text: "" };
    if (line.startsWith("### ")) return { kind: "h3", text: line.slice(4) };
    if (line.startsWith("## ")) return { kind: "h2", text: line.slice(3) };
    if (line.startsWith("# ")) return { kind: "h1", text: line.slice(2) };
    if (/^\s*[-*]\s+/.test(line)) return { kind: "bullet", text: line.replace(/^\s*[-*]\s+/, "") };
    if (/^\s*\d+\.\s+/.test(line)) return { kind: "numbered", text: line.replace(/^\s*\d+\.\s+/, "") };
    return { kind: "text", text: line };
  });
}

function stripMd(text: string): string {
  return text.replace(/\*\*(.*?)\*\*/g, "$1").replace(/`(.*?)`/g, "$1");
}

export async function exportPdf(processName: string, documentationMd: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  const titleLines = doc.splitTextToSize(processName, maxWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 26 + 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Generated by FlowBuilder AI — ${new Date().toLocaleDateString()}`, margin, y);
  doc.setTextColor(20);
  y += 24;

  const png = await snapshotCanvas();
  if (png) {
    try {
      const img = await loadImage(png);
      const ratio = Math.min(maxWidth / img.width, 260 / img.height);
      const w = img.width * ratio;
      const h = img.height * ratio;
      ensureSpace(h + 30);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.text("Process Diagram", margin, y);
      y += 16;
      doc.addImage(png, "JPEG", margin, y, w, h);
      y += h + 24;
    } catch {
      // ignore snapshot failure
    }
  }

  const lines = parseMarkdownLines(documentationMd);
  for (const line of lines) {
    if (line.kind === "blank") {
      y += 6;
      continue;
    }
    if (line.kind === "h1") continue; // already used as title
    if (line.kind === "h2") {
      ensureSpace(28);
      y += 10;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(stripMd(line.text), margin, y);
      y += 18;
      continue;
    }
    if (line.kind === "h3") {
      ensureSpace(22);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11.5);
      const wrapped = doc.splitTextToSize(stripMd(line.text), maxWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 14 + 4;
      continue;
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    const prefix = line.kind === "bullet" ? "•  " : line.kind === "numbered" ? "" : "";
    const wrapped = doc.splitTextToSize(prefix + stripMd(line.text), maxWidth - (line.kind === "bullet" ? 12 : 0));
    ensureSpace(wrapped.length * 13 + 4);
    doc.text(wrapped, margin + (line.kind === "bullet" ? 10 : 0), y);
    y += wrapped.length * 13 + 4;
  }

  doc.save(`${slug(processName)}.pdf`);
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

export async function exportDocx(processName: string, documentationMd: string) {
  const children: Paragraph[] = [];

  children.push(
    new Paragraph({
      text: processName,
      heading: HeadingLevel.TITLE,
    }),
  );
  children.push(
    new Paragraph({
      children: [new TextRun({ text: `Generated by FlowBuilder AI — ${new Date().toLocaleDateString()}`, italics: true, color: "888888" })],
      spacing: { after: 200 },
    }),
  );

  const png = await snapshotCanvas();
  if (png) {
    try {
      const res = await fetch(png);
      const buf = await res.arrayBuffer();
      const img = await loadImage(png);
      const ratio = Math.min(480 / img.width, 300 / img.height, 1);
      children.push(
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new ImageRun({
              type: "jpg",
              data: buf,
              transformation: { width: img.width * ratio, height: img.height * ratio },
            }),
          ],
          spacing: { after: 200 },
        }),
      );
    } catch {
      // ignore
    }
  }

  const lines = parseMarkdownLines(documentationMd);
  for (const line of lines) {
    if (line.kind === "blank") continue;
    if (line.kind === "h1") continue;
    if (line.kind === "h2") {
      children.push(new Paragraph({ text: stripMd(line.text), heading: HeadingLevel.HEADING_1, spacing: { before: 240, after: 100 } }));
      continue;
    }
    if (line.kind === "h3") {
      children.push(new Paragraph({ text: stripMd(line.text), heading: HeadingLevel.HEADING_2, spacing: { before: 160, after: 60 } }));
      continue;
    }
    if (line.kind === "bullet") {
      children.push(new Paragraph({ text: stripMd(line.text), bullet: { level: 0 } }));
      continue;
    }
    if (line.kind === "numbered") {
      children.push(new Paragraph({ text: stripMd(line.text), numbering: { reference: "doc-numbering", level: 0 } }));
      continue;
    }
    children.push(new Paragraph({ text: stripMd(line.text), spacing: { after: 80 } }));
  }

  const doc = new Document({
    numbering: {
      config: [
        {
          reference: "doc-numbering",
          levels: [{ level: 0, format: "decimal", text: "%1.", alignment: AlignmentType.START }],
        },
      ],
    },
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, `${slug(processName)}.docx`);
}
