import { useState } from "react";
import { useApp } from "../lib/store";
import { useFlowActions } from "../lib/actions";
import { IconSparkle, IconPaperclip, IconComment, IconEdit, IconTrash, IconCheck, IconX } from "./icons";

const TYPE_LABEL: Record<string, string> = {
  start: "Start",
  process: "Process",
  decision: "Decision",
  io: "Input / Output",
  end: "End",
};

function timeAgo(ts: number): string {
  const s = Math.max(1, Math.floor((Date.now() - ts) / 1000));
  if (s < 60) return "Just now";
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

export default function InspectorPanel() {
  const { state } = useApp();

  const node = state.model?.nodes.find((n) => n.id === state.selectedNodeId) ?? null;
  const edge = state.model?.edges.find((e) => e.id === state.selectedEdgeId) ?? null;

  if (edge && state.model) {
    return <EdgeInspector edgeId={edge.id} />;
  }

  if (!node) {
    return <OverviewInspector />;
  }

  return <NodeInspector nodeId={node.id} />;
}

function OverviewInspector() {
  const { state } = useApp();
  const model = state.model;
  const decisions = model?.nodes.filter((n) => n.type === "decision").length ?? 0;
  const sources = model?.nodes.reduce((s, n) => s + n.sources.length, 0) ?? 0;
  const comments = (model?.nodes.reduce((s, n) => s + n.comments.length, 0) ?? 0) + state.diagramComments.length;
  const lastUpdated = state.history[state.historyIndex]?.timestamp;

  return (
    <div className="h-full overflow-y-auto scrollbar-none p-4">
      <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-ink-faint">Diagram Overview</h3>
      {model ? (
        <>
          <div className="grid grid-cols-2 gap-2.5">
            <Stat label="Components" value={model.nodes.length} />
            <Stat label="Decisions" value={decisions} />
            <Stat label="Sources" value={sources} />
            <Stat label="Comments" value={comments} />
          </div>
          <div className="mt-4 space-y-1.5 border-t border-border-soft pt-3 text-sm">
            <div className="flex items-center gap-1.5 text-ink-soft">
              <IconSparkle className="h-3.5 w-3.5 text-brand" /> Generated by AI
            </div>
            <div className="text-ink-faint">Last updated {lastUpdated ? timeAgo(lastUpdated) : "just now"}</div>
          </div>
        </>
      ) : (
        <p className="text-sm text-ink-faint">Generate a diagram to see an overview here.</p>
      )}
      <p className="mt-6 text-xs text-ink-faint">Select a component on the canvas to inspect its details, sources, and comments.</p>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-lg border border-border-soft bg-surface-2 px-3 py-2.5">
      <p className="text-lg font-semibold text-ink">{value}</p>
      <p className="text-[11px] text-ink-faint">{label}</p>
    </div>
  );
}

function NodeInspector({ nodeId }: { nodeId: string }) {
  const { state, dispatch } = useApp();
  const actions = useFlowActions();
  const node = state.model!.nodes.find((n) => n.id === nodeId)!;
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState({ label: node.label, description: node.description ?? "", actor: node.actor ?? "" });
  const [instruction, setInstruction] = useState("");
  const modifying = state.modifying && state.modifyingNodeId === nodeId;

  function startEdit() {
    setDraft({ label: node.label, description: node.description ?? "", actor: node.actor ?? "" });
    setEditing(true);
  }
  function saveEdit() {
    actions.updateNodeManually(nodeId, draft);
    setEditing(false);
  }

  function submitModify() {
    if (!instruction.trim()) return;
    dispatch({ type: "SET_MODIFYING_NODE", id: nodeId });
    actions.handleModifyRequest(nodeId, instruction.trim());
    setInstruction("");
  }

  return (
    <div className="flex h-full flex-col">
      <div className="border-b border-border-soft p-4">
        <div className="mb-1 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-ink-faint">
          Selected Component
          {node.aiGenerated && (
            <span className="flex items-center gap-0.5 rounded-full bg-brand-soft px-1.5 py-0.5 text-[10px] font-medium text-brand-deep">
              <IconSparkle className="h-2.5 w-2.5" /> AI
            </span>
          )}
        </div>
        {editing ? (
          <input
            value={draft.label}
            onChange={(e) => setDraft((d) => ({ ...d, label: e.target.value }))}
            className="w-full rounded-md border border-brand px-2 py-1.5 text-base font-semibold text-ink outline-none"
          />
        ) : (
          <h3 className="text-base font-semibold text-ink">{node.label}</h3>
        )}
      </div>

      <div className="flex-1 overflow-y-auto scrollbar-none p-4 space-y-4">
        <Field label="Type" value={TYPE_LABEL[node.type]} />
        <div>
          <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-ink-faint">Actor</p>
          {editing ? (
            <input
              value={draft.actor}
              onChange={(e) => setDraft((d) => ({ ...d, actor: e.target.value }))}
              className="w-full rounded-md border border-border px-2 py-1.5 text-sm text-ink outline-none focus:border-brand"
              placeholder="Assign an owner"
            />
          ) : (
            <p className="text-sm text-ink">{node.actor || "—"}</p>
          )}
        </div>
        <div>
          <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-ink-faint">Description</p>
          {editing ? (
            <textarea
              value={draft.description}
              onChange={(e) => setDraft((d) => ({ ...d, description: e.target.value }))}
              rows={3}
              className="w-full resize-none rounded-md border border-border px-2 py-1.5 text-sm text-ink outline-none focus:border-brand"
            />
          ) : (
            <p className="text-sm text-ink-soft">{node.description || "No description yet."}</p>
          )}
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => dispatch({ type: "SET_EVIDENCE_NODE", id: nodeId })}
            disabled={node.sources.length === 0}
            className="flex items-center gap-1.5 rounded-md border border-border-soft bg-surface-2 px-2.5 py-1.5 text-xs font-medium text-ink-soft hover:bg-border-soft disabled:opacity-40"
          >
            <IconPaperclip className="h-3.5 w-3.5" /> Sources <span className="font-semibold">{node.sources.length}</span>
          </button>
          <button
            onClick={() => {
              dispatch({ type: "SET_COMMENTS_TARGET", target: { scope: "node", nodeId } });
              dispatch({ type: "SET_RIGHT_PANEL_MODE", mode: "comments" });
            }}
            className="flex items-center gap-1.5 rounded-md border border-border-soft bg-surface-2 px-2.5 py-1.5 text-xs font-medium text-ink-soft hover:bg-border-soft"
          >
            <IconComment className="h-3.5 w-3.5" /> Comments <span className="font-semibold">{node.comments.length}</span>
          </button>
        </div>

        {editing ? (
          <div className="flex gap-2">
            <button onClick={saveEdit} className="flex items-center gap-1 rounded-md bg-brand px-3 py-1.5 text-xs font-medium text-white hover:bg-brand-deep">
              <IconCheck className="h-3.5 w-3.5" /> Save
            </button>
            <button onClick={() => setEditing(false)} className="flex items-center gap-1 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-ink-soft hover:bg-surface-2">
              <IconX className="h-3.5 w-3.5" /> Cancel
            </button>
          </div>
        ) : (
          <div className="flex gap-2">
            <button onClick={startEdit} className="flex items-center gap-1 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-ink-soft hover:bg-surface-2">
              <IconEdit className="h-3.5 w-3.5" /> Edit
            </button>
            {node.type !== "start" && node.type !== "end" && (
              <button
                onClick={() => {
                  if (confirm(`Delete "${node.label}"? Connections will be rewired automatically.`)) actions.deleteNodeManually(nodeId);
                }}
                className="flex items-center gap-1 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-danger hover:bg-danger-soft"
              >
                <IconTrash className="h-3.5 w-3.5" /> Delete
              </button>
            )}
          </div>
        )}
      </div>

      <div className="border-t border-border-soft p-4">
        <p className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-ink-faint">
          <IconSparkle className="h-3.5 w-3.5 text-brand" /> Ask AI to Modify
        </p>
        <textarea
          value={instruction}
          onChange={(e) => setInstruction(e.target.value)}
          placeholder="Tell AI how you want to modify this step…"
          rows={2}
          className="w-full resize-none rounded-md border border-border bg-surface-2 px-2.5 py-2 text-sm text-ink placeholder:text-ink-faint outline-none focus:border-brand focus:bg-surface"
        />
        <button
          onClick={submitModify}
          disabled={modifying || !instruction.trim()}
          className="mt-2 flex w-full items-center justify-center gap-1.5 rounded-md bg-brand px-3 py-2 text-sm font-medium text-white hover:bg-brand-deep disabled:opacity-50"
        >
          {modifying ? (
            <>
              <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-white border-t-transparent" />
              AI is updating "{node.label}"…
            </>
          ) : (
            <>
              <IconSparkle className="h-3.5 w-3.5" /> Ask AI to Modify
            </>
          )}
        </button>
      </div>
    </div>
  );
}

function EdgeInspector({ edgeId }: { edgeId: string }) {
  const { state } = useApp();
  const actions = useFlowActions();
  const edge = state.model!.edges.find((e) => e.id === edgeId)!;
  const from = state.model!.nodes.find((n) => n.id === edge.from);
  const to = state.model!.nodes.find((n) => n.id === edge.to);
  const [label, setLabel] = useState(edge.label ?? "");

  return (
    <div className="p-4 space-y-4">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-ink-faint">Connection</h3>
      <div className="rounded-lg border border-border-soft bg-surface-2 p-3 text-sm">
        <p className="font-medium text-ink">{from?.label}</p>
        <p className="my-1 text-ink-faint">↓</p>
        <p className="font-medium text-ink">{to?.label}</p>
      </div>
      <div>
        <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-ink-faint">Label</p>
        <div className="flex gap-2">
          <input
            value={label}
            onChange={(e) => setLabel(e.target.value)}
            placeholder="e.g. Yes / No"
            className="min-w-0 flex-1 rounded-md border border-border px-2.5 py-1.5 text-sm outline-none focus:border-brand"
          />
          <button
            onClick={() => actions.relabelEdge(edgeId, label)}
            className="rounded-md bg-brand px-3 py-1.5 text-xs font-medium text-white hover:bg-brand-deep"
          >
            Save
          </button>
        </div>
      </div>
      <button
        onClick={() => actions.deleteEdge(edgeId)}
        className="flex items-center gap-1 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-danger hover:bg-danger-soft"
      >
        <IconTrash className="h-3.5 w-3.5" /> Delete connection
      </button>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-ink-faint">{label}</p>
      <p className="text-sm text-ink">{value}</p>
    </div>
  );
}
