#!/usr/bin/env node
/**
 * Scans public/garments/<garment>/ for artwork PNGs and writes a typed
 * registry to src/data/designs.generated.ts. This is what makes "drop a PNG
 * in the folder, it shows up as a selectable design" true — nothing about an
 * individual file is hardcoded anywhere else in the app.
 *
 * Excluded by name (case-insensitive, any of these basenames): the
 * photographic compositor layers that live alongside the artwork in the same
 * folder (base/mask/shadow(s)/highlight(s)) and reference/preview images.
 * Everything else ending in .png is treated as a selectable design.
 *
 * Naming convention (all optional):
 *   - "<category>--<slug>.png"  -> category + slug both taken from the name
 *   - "<slug>.png"               -> category defaults to "Original"
 *   - anything that doesn't look like a human-chosen name (e.g. a raw
 *     "ChatGPT Image ..." export filename, or a filename with no letters)
 *     falls back to "Design 01", "Design 02", ... in filename order, so
 *     auto-exported files still get a readable label instead of their literal
 *     export filename.
 *
 * Run automatically by `npm run dev` / `npm run build` (see package.json) so
 * the registry never goes stale; also runnable directly as
 * `node scripts/generate-designs.mjs`.
 */

import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const GARMENTS_DIR = join(ROOT, "public", "garments");
const OUT_FILE = join(ROOT, "src", "data", "designs.generated.ts");

const EXCLUDED_BASENAMES = new Set(["base", "mask", "shadow", "shadows", "highlight", "highlights", "reference", "preview"]);

// Curated display names for specific known exports — purely cosmetic polish,
// never required: any file not listed here still gets a perfectly usable
// generated name via slugify()/fallback below.
const KNOWN_NAME_OVERRIDES = {
  "ChatGPT Image Sep 17, 2026, 04_23_29 PM (1).png": { name: "Midnight Tokyo — Neon District", category: "Streetwear" },
  "ChatGPT Image Sep 17, 2026, 04_23_30 PM (2).png": { name: "Midnight Tokyo — After Dark", category: "Streetwear" },
};

function looksAutoGenerated(base) {
  // Raw exports from image tools ("ChatGPT Image ...", "IMG_1234", "Untitled (3)")
  // carry no real design name — treat anything without a letter run of 3+
  // outside such a pattern, or matching these tool prefixes, as unnamed.
  return /^(chatgpt image|img_|image|untitled|screenshot)/i.test(base.trim());
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function titleCase(slug) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

function buildDesignsForGarment(garment) {
  const dir = join(GARMENTS_DIR, garment);
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }

  const pngFiles = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith(".png"))
    .map((e) => e.name)
    .filter((name) => !EXCLUDED_BASENAMES.has(name.replace(/\.png$/i, "").toLowerCase()))
    .sort();

  let fallbackIndex = 0;
  return pngFiles.map((filename) => {
    const override = KNOWN_NAME_OVERRIDES[filename];
    const base = filename.replace(/\.png$/i, "");

    let category = "Original";
    let namePart = base;
    const sepIndex = base.indexOf("--");
    if (sepIndex !== -1) {
      category = titleCase(slugify(base.slice(0, sepIndex))) || category;
      namePart = base.slice(sepIndex + 2);
    }

    const slug = slugify(namePart);
    const usableName = !override && (looksAutoGenerated(namePart) || !slug) ? null : titleCase(slug);

    fallbackIndex += 1;
    const name = override?.name ?? usableName ?? `Design ${String(fallbackIndex).padStart(2, "0")}`;
    const id = override ? slugify(override.name) : slug || `design-${fallbackIndex}`;

    return {
      id,
      name,
      // encodeURI so filenames with spaces/commas (e.g. raw tool exports)
      // resolve correctly as URLs — the registry's `image` is used directly
      // as an <img>/Image() src.
      image: encodeURI(`/garments/${garment}/${filename}`),
      category: override?.category ?? category,
    };
  });
}

const GARMENT_KINDS = ["tshirt", "hoodie", "cap"];
const registry = {};
for (const kind of GARMENT_KINDS) {
  const designs = buildDesignsForGarment(kind);
  if (designs.length) registry[kind] = designs;
}

const header = `/**
 * AUTO-GENERATED by scripts/generate-designs.mjs — do not edit by hand.
 * Regenerated on every \`npm run dev\` / \`npm run build\`. To add a design,
 * drop a PNG into public/garments/<garment>/ and restart the dev server (or
 * just rebuild) — nothing here needs to change by hand.
 */

export interface DesignAsset {
  id: string;
  name: string;
  /** Public path to the artwork PNG, e.g. "/garments/tshirt/samurai.png". */
  image: string;
  category: string;
}

export type DesignGarmentKind = ${GARMENT_KINDS.map((k) => JSON.stringify(k)).join(" | ")};
`;

const body = `
export const DESIGN_REGISTRY: Partial<Record<DesignGarmentKind, DesignAsset[]>> = ${JSON.stringify(registry, null, 2)};

export function designsFor(garment: DesignGarmentKind): DesignAsset[] {
  return DESIGN_REGISTRY[garment] ?? [];
}

export function designById(garment: DesignGarmentKind, id: string): DesignAsset | undefined {
  return designsFor(garment).find((d) => d.id === id);
}
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, header + body);

const total = Object.values(registry).reduce((sum, list) => sum + list.length, 0);
console.log(`[generate-designs] wrote ${total} design(s) across ${Object.keys(registry).length} garment(s) to src/data/designs.generated.ts`);
